"""add: images table column

Revision ID: 8a28a84a2f0b
Revises: 27a315017373
Create Date: 2023-08-29 11:38:28.579406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a28a84a2f0b'
down_revision = '27a315017373'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Images', sa.Column('bucket_string', sa.String(length=255), nullable=True))
    op.add_column('Images', sa.Column('bucket_folder', sa.String(length=255), nullable=True))
    op.add_column('Images', sa.Column('image_url', sa.String(length=255), nullable=True))
    op.add_column('Images', sa.Column('bucket', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Images', 'bucket')
    op.drop_column('Images', 'image_url')
    op.drop_column('Images', 'bucket_folder')
    op.drop_column('Images', 'bucket_string')
    # ### end Alembic commands ###
